### ISSUE TITLE
Invalid URI scheme: URI must begin with 'mongodb://' or 'mongodb+srv://

### ISSUE THREAD

**Issue by vaibhav293** [pyeve/eve#1179] opened 2018-08-02 14:44 UTC
We are running eve in a docker container and connecting to mongo using MONGO_URI ( not as depending mongodb docker). We keep getting the following error: 

```
({'status': 'ERR', '_error': {'code': 500, 'message': "Error in getting user Invalid URI scheme: URI must begin with 'mongodb://' or 'mongodb+srv://'"}}, {'url': 'http://localhost:9001/api/v1/users/ecc1a', 'environ': {'HTTP_HOST': 'localhost:9001', 'REMOTE_PORT': 58994, 'wsgi.multithread': False, 'werkzeug.request': <Request 'http://localhost:9001/api/v1/users/ecc1a' [GET]>, 'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'>, 'wsgi.input': <_io.BufferedReader name=7>, 'CONTENT_TYPE': 'application/json', 'QUERY_STRING': '', 'HTTP_USER_AGENT': 'PostmanRuntime/7.1.1', 'SCRIPT_NAME': '', 'HTTP_POSTMAN_TOKEN': '6992a8f2-9a7f-4788-b90d-02e121a91a62', 'CONTENT_LENGTH': '', 'HTTP_CONNECTION': 'keep-alive', 'HTTP_ACCEPT': 'application/json', 'wsgi.version': (1, 0), 'REQUEST_METHOD': 'GET', 'SERVER_SOFTWARE': 'Eve/0.7.4 Werkzeug/0.11.15', 'werkzeug.server.shutdown': <function WSGIRequestHandler.make_environ.<locals>.shutdown_server at 0x7fa9569e8598>, 'PATH_INFO': '/api/v1/users/4fe482ef7d5a5de0511be4d7b24ecc1a', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate', 'SERVER_PROTOCOL': 'HTTP/1.1', 'REMOTE_ADDR': '172.17.0.1', 'wsgi.url_scheme': 'http', 'HTTP_CACHE_CONTROL': 'no-cache', 'wsgi.run_once': False, 'SERVER_NAME': '0.0.0.0', 'wsgi.multiprocess': False, 'SERVER_PORT': '5000'}, 'url_rule': <Rule '/api/v1/users/<user_id>/' (OPTIONS, HEAD, GET) -> get_user>, 'shallow': False, 'view_args': {'user_id': 'ecc1a'}})
```

If we run the same without docker then our code works without any issues. 

Our Dockerfile looks like this:

```
FROM python:3.4.3

RUN mkdir -p /usr/src/user-service

WORKDIR /usr/src/user-service

COPY . /usr/src/user-service

RUN pip install -r requirements.txt

CMD ["python","-v","application.py"]
```

### Environment

* Python version: 3.4.3
* Eve version: 0.7.4

**Comment by jwfuller** [comment] 2018-08-06 16:42
@vaibhav293 Is this a duplicate of https://github.com/pyeve/eve/issues/1172? I was getting a similar error and updating to 0.7.10 resolved it for me.

**Comment by nicolaiarocci** [comment] 2018-08-06 17:01
Most likely. Probably, when running out of the container, you are using an older version of Flask-PyMongo.

**Closed by nicolaiarocci** 2018-08-06 17:01 UTC
Labels: duplicate
