### ISSUE TITLE
default_sort doesn't work

### ISSUE THREAD

**Issue by zhangtemplar** [pyeve/eve#1085] opened 2017-11-09 07:22 UTC
I find default_sort doesn't work, e.g., I am using the following configuration for the end point:
```
newsSchema = {
    'datasource': {
        'source': 'news',
        'default_sort': [("time", -1)],  # sort the field by time from recent to old.
    },
}
```
The global setting for sort is not set, so it uses the default true.

However, attaching the `sort` to the query url works:

```
        if (endPoint.includes("?")) {
            endPoint += "&sort=-time";
        } else {
            endPoint += "?sort=-time";
        }
        fetch(
            SERVER_URL + endPoint,
            sentData
        )
```

**Comment by nicolaiarocci** [comment] 2017-11-09 13:57
I cannot reproduce this. Are you sure you are consuming the 'news' endpoint in your tests? And also, that `newSchema` is actually attached to 'news' endpoint definition?

**Comment by zhangtemplar** [comment] 2017-11-10 04:01
@nicolaiarocci i am sure i am consuming the news endpoint.

**Comment by rmlopes** [comment] 2018-07-27 14:37
I have this issue as well. My package versions are as follows:
```
Cerberus==1.2
Eve==0.8
Flask==1.0.2
Flask-Bootstrap==3.3.7.1
Flask-OAuthlib==0.9.3
Flask-PyMongo==0.5.2
Flask-Sentinel==0.0.7
jsonschema==2.6.0
lxml==4.2.1
oauthlib==2.1.0
pymongo==3.6.1
redis==2.10.6
request==1.0.2
requests==2.18.4
requests-oauthlib==1.0.0
simplegeneric==0.8.1
simplejson==3.15.0
six==1.11.0
tornado==5.0.2
tox==2.5.0
urllib3==1.22
virtualenv==16.0.0
Werkzeug==0.14.1
```

I am using it like so:
```python
DOMAIN = {
'aresource': {
        'description': 'a description.',
        'schema': {
            'somelabel': {'type': 'string'},
        },
        'datasource': {'default_sort': [('_created',-1)]},
    },
}
```

**Comment by nicolaiarocci** [comment] 2018-08-01 13:15
@rmlopes I see that you use 'aresource' instead of 'datesource'. Is that a typo or the copy & paste from your actual settings?

**Comment by nicolaiarocci** [comment] 2018-08-01 13:18
@rmlopes does the `_created` field exist on all of your documents?

**Comment by rmlopes** [comment] 2018-08-01 13:34
@nicolaiarocci It does (it is automatically generated). I've tried the same using the `_id` and it also does not work. I have a  workaround for my use case, but I think it is something that should be sorted out :)

**Comment by nicolaiarocci** [comment] 2018-08-01 13:42
And `sorting` is active for the resource (it is by default)?

**Comment by rmlopes** [comment] 2018-08-01 13:45
It is. I also tried to make it explicitly (despite the default) both through the global flag, and through the resource property, but made no difference.

**Comment by nicolaiarocci** [comment] 2018-08-01 13:53
And yet [this test](https://github.com/pyeve/eve/blob/master/eve/tests/methods/get.py#L555) does pass, even when replacing `prog` with one `_id`. Hmm.

**Comment by nicolaiarocci** [comment] 2018-08-01 14:02
Once again I cannot reproduce this. I am (re)closing the ticket, ready to re-open as needed. If any of you two could PR a failing test (and, maybe, even the fix!), that would really help.

**Closed by nicolaiarocci** 2018-08-01 14:02 UTC

**Comment by nicolaiarocci** [comment] 2018-08-01 16:29
I also tried the direct settings file approach, and it worked for me. Can you please post your setting file, or email it to me at eve@nicolaiarocci.com

**Comment by rmlopes** [comment] 2018-08-01 16:49
Ok, I found the issue with my file. I had the `datasource` field inside the `schema` by mistake. By the looks of it, should be the same problem with the original issue posted. Thanks,, @nicolaiarocci

**Comment by nicolaiarocci** [comment] 2018-08-01 17:59
You are very welcome
